default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40344_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_40344_test

production:
  <<: *default
  database: furima_40344_production
  username: furima_40344
  password: <%= ENV["FURIMA_123_DATABASE_PASSWORD"] %>